name: alarm_dungeon
description: "A gamified alarm app: Alarm Dungeon"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  audioplayers: ^6.7.1
  vibration: ^3.1.8
  alarm: ^5.4.1
  permission_handler: ^12.0.3
  android_intent_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/monster/
    - assets/audio/

